name: CD

on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v3
      - name: Add node binary
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build
      - name: Copy build to server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: './dist'
          target: '/var/www'
