name: CD

on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v3
      - name: Add node binary
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build
      - name: Copy build to server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'gebrish'
      - name: adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: use rsynx
        run: rsync -avz ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/capp/
        
