name: CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
    
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: add node
        uses: actions/setup-node@v3
      - run: npm run ci
      - run: npm run build --if-present
      - run: npm run test
  
