name: CI workflow

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v3
      - name: Add node binary
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
