name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-and-test:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: run-and-test
    uses: ./.github/workflows/cd.yml
